ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS last_broadcast_score TEXT;
ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS half_time_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS daily_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS reminder_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS result_sent BOOLEAN DEFAULT FALSE;
